const icHome = 'assets/icons/ic_home.svg';
const icSkills = 'assets/icons/ic_skills.svg';
const icContact = 'assets/icons/ic_contact.svg';
const icProjects = 'assets/icons/ic_code.svg';
const icBlogs = 'assets/icons/ic_blogs.svg';
const icAppIcon = 'assets/icons/ic_app_icon.svg';
const icDownload ='assets/icons/ic_download.svg';
const icDarkThemeEnabled  ='assets/icons/ic_dark_mode_enabled.svg';
const icLightThemeEnabled = 'assets/icons/ic_light_mode_enabled.svg';