const logoText = 'SZ';
const title = 'Sheraz Ali';
const shortDescription = 'Flutter App Developer – I Design and Develop Mobile Apps to Elevate Your Business – Book a Free Consultation Today';
const aboutMe = '''I am a self-taught mobile app developer with over 3 years of experience, specializing in Flutter and Native Android App Development. My portfolio spans various industries, including AI-powered applications utilizing ChatGPT and real-time Text-to-Speech APIs, E-commerce platforms, Language Translation tools, Chat and Video Communication apps, Stock Market applications with integrated AI Chatbots, and apps for reading and listening to book summaries. I have successfully delivered projects to clients worldwide and have a passion for learning new technologies, continually exploring new trends and innovations in the tech space. ''';
const aboutMeMobileDescription = '''Self-taught mobile app developer with 3+ years of experience, specializing in Flutter and Native Android. I’ve worked across various industries, including AI apps with ChatGPT and Text-to-Speech, E-commerce, Translation, Communication, Stock Market, and book summary apps. Passionate about learning and exploring new technologies.''';

const experienceDescription = 'Years of experience. Specialised in building apps, while ensuring a seamless experience for end users.';
const profileUrl = 'https://images.unsplash.com/photo-1619241805829-34fb64299391?q=80&w=3024&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D';

const marketsAIDescription = '''MarketSAI is a cutting-edge mobile application designed to empower retail investors with the same AI-driven insights traditionally reserved for professional investors and hedge funds. It efficiently filters and summarizes vast amounts of financial news and data, presenting actionable insights on top U.S. stocks and limited international coverage. Key features include AI-driven insights, real-time data monitoring, visually engaging data presentation, and premium tools like multiple chart views and trade tracking ''';
const happyLifeDescription = 'Happylife is poised to become the top book summary app, offering concise insights from over 5,500 nonfiction bestsellers, 100+ TED Talks, and 100+ podcasts. Designed for fast learning and self-growth, the app provides daily microlearning sessions, self-growth challenges, and a personalized content approach tailored to individual goals. Key features include high-quality summaries, content from reputable sources, spaced repetition for better retention, and an offline mode for learning on the go. Happylife is a community-focused platform aimed at helping users achieve their goals and become the best versions of themselves.';

const konushanDescription = '''Konushan is a language learning app that offers a wide range of languages, including English, Turkish, French, Arabic, German, and more. My contribution to the project includes:

Language Learning Community: Connecting users with a global community of language learners, making language acquisition a social experience.
Instant Message Translation: Implementing an in-app translation tool to instantly translate messages and overcome language barriers.
Global Language Exchange: Facilitating engagement with native speakers worldwide to enhance conversational skills.
AI-Powered Chat: Integrating AI-powered chat to allow users to practice languages in multiple languages, making learning interactive and enjoyable.''';

const codeOfCivilProcedureDescription = '''The "Code of Civil Procedure 1908 (CPC)" app is a comprehensive, free, and offline resource designed to help users learn about India's civil procedural law. It provides detailed, section-wise, and chapter-wise legal information, including the latest amendments. The app covers all aspects of the Code, which is divided into two parts: 158 sections outlining general jurisdiction principles and a First Schedule with 51 Orders and Rules governing civil proceedings.

Key features include offline access, advanced search, text-to-speech, the ability to add and share notes, and options to resize text or save sections as PDFs. This user-friendly app is ideal for legal professionals, students, and anyone interested in Indian law, offering an accessible and regularly updated digital version of the Code of Civil Procedure. ''';

const customTeesDescription = 'PRINT-ON-DEMAND Custom T-Shirt is an android application that allows users to design personalized T-shirts with ease. The app offers a comprehensive set of customization tools, including options to change the T-shirt color, add text with any font and size, and incorporate logos, images, and stickers into the design. Once the user finalizes their design, they can specify the size and quantity of the T-shirts and place an order directly through the app. This application is ideal for anyone looking to create custom apparel for personal use, events, or as unique gifts.';
const hitchDescription = 'Hitch is a new way for pickleball and tennis players to connect with other players nearby at their level. Swipe through player cards to find your match, then send and receive "Hitch" requests to message other players and find courts - let’s play!';
const arabVetDescription = ''' The Arab Vet app is a dedicated platform for Arabic-speaking pet owners, offering easy access to online veterinary consultations. Users can connect with certified veterinarians through text or video chats for expert advice on their pets' health. The app features personalized pet profiles, health monitoring, customized recommendations, and a record of previous consultations for easy reference. With a user-friendly interface, Arab Vet makes it simple to manage your pets' well-being from the comfort of your home, anytime and anywhere. ''';

const tobuildExperienceDescription = 'I am currently serving as the Lead Flutter mobile app developer at Tobuild LLC, where I\'ve successfully developed multiple applications, and launched Hitch Player Finder and Markets AI';
const freelanceExperienceDescription = 'I began my freelancing career in 2020 on Fiverr and Upwork, initially focusing on developing native Android applications. Over time, I expanded my expertise to include cross-platform application development and transitioned my services accordingly. I have successfully developed and published several Flutter framework applications, including "Konushan-Language Exchange" and "HappyLife: Book Summaries." available on App store and Play store.';
const myEmail = 'soomrosheraz054@gmail.com';
const myContactNum = '+92 307 2215 500';
const myResumeLink = 'https://drive.google.com/file/d/1--Dw5DlBCbVna4Rv9-emFEcKYZol_b-H/view?usp=sharing';
const myGitHubLink ='https://github.com/SherazAli-67';
const myLinkedInLink = 'https://www.linkedin.com/in/sherazalisoomro/';
const myTwitterLink = 'https://x.com/SherazNazir7';